services:
  traefik:
    image: traefik:v2.10  
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"  
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"  
    ports:
      - "80:80"
      - "8085:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - webapp-network

networks:
  webapp-network:
    external: true
    name: web-apps_default