global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'diegolopezmiguelanez@gmail.com'
  smtp_auth_username: 'diegolopezmiguelanez@gmail.com'
  smtp_auth_password: 'uqpavfleqkfymisg'  # App Password

route:
  receiver: 'email-alerts'   # receptor inicial
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  routes:
    # Enviar también a Slack
    - receiver: 'slack-alerts'
      continue: true

    # Enviar también a n8n
    - receiver: 'n8n-webhook'
      continue: true

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'diegolopezmiguelanez@gmail.com'
        send_resolved: true

  - name: 'slack-alerts'
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: '#alertas-prometheus'
        send_resolved: true
        title: "⚠️ Prometheus Alert"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Severity:* {{ .Labels.severity }}
          *Status:* {{ .Status }}
          *Description:* {{ .Annotations.description }}
          *Starts At:* {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
          {{ end }}


  - name: 'n8n-webhook'
    webhook_configs:
      - url: "http://n8n:5678/webhook/alert"
        send_resolved: true
