version: "3.9"

services:
  zabbix-db:
    image: postgres:15
    container_name: zabbix-db
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      TZ: America/New_York
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - web-apps_default

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4.0
    container_name: zabbix-server
    depends_on: [zabbix-db]
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      TZ: America/New_York
    ports: ["10051:10051"]
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    networks:
      - web-apps_default

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4.0
    container_name: zabbix-web
    depends_on: [zabbix-server]
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/New_York
      TZ: America/New_York
    ports: ["8080:8080"]
    networks:
      - web-apps_default

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports: ["9090:9090"]
    environment:
      TZ: America/New_York
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    networks:
      - web-apps_default

  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    ports: ["9093:9093"]
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    depends_on: [prometheus]
    environment:
      TZ: America/New_York
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    networks:
      - web-apps_default

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      TZ: America/New_York
    depends_on: [prometheus, zabbix-server]
    ports: ["3000:3000"]
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - web-apps_default

  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://zabbix:zabbix@zabbix-db:5432/zabbix?sslmode=disable"
    ports: ["9187:9187"]
    depends_on: [zabbix-db]
    networks:
      - web-apps_default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports: ["8086:8080"]
    networks:
      - web-apps_default

volumes:
  zabbix-db-data:
  zabbix-server-data:
  grafana-data:
  prometheus-data:
  alertmanager-data:

networks:
  web-apps_default:
    external: true
