-- Seed data para la tabla contacts - 70 entradas variadas
INSERT INTO contacts (name, email, message, created_at) VALUES
('María González', 'maria.gonzalez@email.com', 'Me encanta el diseño del blog, muy limpio y profesional. ¿Planean añadir más categorías pronto?', NOW() - INTERVAL '70 days'),
('Carlos Rodríguez', 'c.rodriguez@techcorp.com', 'Excelente contenido sobre DevOps. ¿Tienen tutoriales más avanzados sobre Kubernetes?', NOW() - INTERVAL '69 days'),
('Ana López', 'analopez@universidad.edu', 'Estoy haciendo mi tesis sobre automatización IT y su blog me ha sido de gran ayuda. Gracias!', NOW() - INTERVAL '68 days'),
('David Chen', 'davidchen@startup.io', 'Interesante artículo sobre Docker Compose. ¿Podrían cubrir Docker Swarm también?', NOW() - INTERVAL '67 days'),
('Elena Martínez', 'e.martinez@gmail.com', 'El formulario de contacto funciona perfectamente. Muy buena implementación técnica.', NOW() - INTERVAL '66 days'),
('Javier Ruiz', 'jruiz@sistemas.com', 'Busco colaboradores para un proyecto open source de monitoring. ¿Les interesaría?', NOW() - INTERVAL '65 days'),
('Laura García', 'laura.garcia@consulting.es', '¿Ofrecen servicios de consultoría en infraestructura DevOps? Nuestra empresa está interesada.', NOW() - INTERVAL '64 days'),
('Miguel Ángel Santos', 'masantos@itdept.org', 'Problema con la base de datos en producción. ¿Pueden ayudar con optimización de queries?', NOW() - INTERVAL '63 days'),
('Sofía Hernández', 'sofia.h@empresa.com', 'Me gustaría suscribirme al newsletter. ¿Dónde puedo encontrar el formulario?', NOW() - INTERVAL '62 days'),
('Roberto Díaz', 'roberto.diaz@devteam.com', 'Excelente arquitectura de la aplicación. ¿Usaron algún patrón específico para el backend?', NOW() - INTERVAL '61 days'),

('Isabel Torres', 'isabel.t@email.com', 'El artículo sobre Prometheus fue revelador. ¿Tienen métricas específicas para bases de datos?', NOW() - INTERVAL '60 days'),
('Fernando López', 'fernando.l@tech.io', 'Interesante ver el uso de Traefik. ¿Lo recomiendan sobre Nginx para microservicios?', NOW() - INTERVAL '59 days'),
('Patricia Morales', 'pmorales@company.com', '¿Tienen documentación sobre la API? Me gustaría integrarla con nuestra aplicación.', NOW() - INTERVAL '58 days'),
('Alejandro Jiménez', 'alejandro.j@startup.com', 'Busco mentores para un proyecto de infraestructura como código. ¿Ofrecen mentoring?', NOW() - INTERVAL '57 days'),
('Carmen Vargas', 'carmen.v@corp.es', 'El rendimiento del sitio es excelente. ¿Podrían compartir técnicas de optimización?', NOW() - INTERVAL '56 days'),
('Ricardo Silva', 'ricardo.silva@it.com', 'Problema con la configuración de Redis. ¿Tienen ejemplos de uso con Django?', NOW() - INTERVAL '55 days'),
('Eva Romero', 'eva.romero@web.dev', 'Me encanta la paleta de colores del blog. ¿Podrían compartir los códigos?', NOW() - INTERVAL '54 days'),
('Daniel Ortega', 'd.ortega@sysadmin.net', 'Excelente tutorial sobre Ansible. ¿Tienen playbooks para entornos multi-cloud?', NOW() - INTERVAL '53 days'),
('Olga Ramírez', 'olga.ramirez@edu.es', 'Estoy enseñando DevOps en la universidad. ¿Puedo usar sus artículos como material?', NOW() - INTERVAL '52 days'),
('Sergio Molina', 'sergio.m@consulting.com', 'Interesante enfoque en el último artículo. ¿Basado en experiencia real?', NOW() - INTERVAL '51 days'),

('Nuria Castillo', 'nuria.castillo@email.com', 'El sistema de comentarios es muy intuitivo. ¿Desarrollado internamente?', NOW() - INTERVAL '50 days'),
('Pablo Reyes', 'pablo.reyes@dev.com', '¿Soportan WebSockets en su arquitectura actual? Estamos evaluando opciones.', NOW() - INTERVAL '49 days'),
('Raquel Medina', 'r.medina@tech.com', 'Excelente documentación técnica. ¿Usan Swagger/OpenAPI para la API?', NOW() - INTERVAL '48 days'),
('Jorge Navarro', 'jorge.navarro@corp.io', 'Problemas de latencia en algunas consultas. ¿Recomiendan algún tipo de índice?', NOW() - INTERVAL '47 days'),
('Mónica Herrera', 'monica.h@startup.es', 'Me interesa la parte de CI/CD. ¿Tienen ejemplos con GitLab CI?', NOW() - INTERVAL '46 days'),
('Andrés Castro', 'andres.castro@it.org', 'El artículo sobre monitorización fue muy útil. ¿Recomiendan Grafana sobre otras?', NOW() - INTERVAL '45 days'),
('Beatriz Ortega', 'beatriz.o@company.com', '¿Ofrecen soporte para implementar esta arquitectura en AWS?', NOW() - INTERVAL '44 days'),
('Héctor Delgado', 'hector.d@techcorp.com', 'Interesante uso de contenedores. ¿Tienen experiencia con Kubernetes en producción?', NOW() - INTERVAL '43 days'),
('Silvia Marín', 'silvia.marin@web.com', 'La velocidad de carga es impresionante. ¿Qué técnicas de caching usan?', NOW() - INTERVAL '42 days'),
('Victor Pérez', 'victor.perez@devteam.com', '¿Planean añadir autenticación OAuth2 en el futuro?', NOW() - INTERVAL '41 days'),

('Adriana Ríos', 'adriana.rios@email.com', 'Excelente trabajo con la base de datos. ¿Qué estrategia usan para backups?', NOW() - INTERVAL '40 days'),
('Francisco Cruz', 'francisco.c@sys.com', 'Problema con conexiones persistentes. ¿Configuran keepalive en el load balancer?', NOW() - INTERVAL '39 days'),
('Teresa Mendoza', 'teresa.mendoza@corp.com', 'Me gusta el diseño responsive. ¿Usan CSS grid o flexbox?', NOW() - INTERVAL '38 days'),
('Gabriel Soto', 'gabriel.soto@it.io', 'Interesante artículo sobre seguridad. ¿Tienen guías para hardening de servidores?', NOW() - INTERVAL '37 days'),
('Rosa Vega', 'rosa.vega@tech.edu', 'Estoy aprendiendo Docker. ¿Recomiendan algún curso adicional?', NOW() - INTERVAL '36 days'),
('Manuel Reyes', 'manuel.reyes@dev.com', 'El sistema de logging es robusto. ¿Usan ELK stack o alguna alternativa?', NOW() - INTERVAL '35 days'),
('Lorena Campos', 'lorena.campos@web.io', '¿Soportan internacionalización en la aplicación?', NOW() - INTERVAL '34 days'),
('Oscar Morales', 'oscar.m@startup.com', 'Excelente performance en móviles. ¿Usan PWA techniques?', NOW() - INTERVAL '33 days'),
('Clara Reyes', 'clara.reyes@email.com', 'Me interesa la escalabilidad. ¿Han probado auto-scaling?', NOW() - INTERVAL '32 days'),
('José Luis Torres', 'jltorres@corp.es', 'Problema con transacciones en la BD. ¿Usan isolation levels específicos?', NOW() - INTERVAL '31 days'),

('Alicia Moreno', 'alicia.moreno@tech.com', 'El diseño UX es excelente. ¿Tienen un equipo dedicado?', NOW() - INTERVAL '30 days'),
('Marcos Rodríguez', 'marcos.r@dev.org', 'Interesante uso de migraciones. ¿Usan alguna herramienta específica?', NOW() - INTERVAL '29 days'),
('Elena Santos', 'elena.santos@web.com', '¿Planean añadir más integraciones con terceros?', NOW() - INTERVAL '28 days'),
('Alberto Cruz', 'alberto.cruz@it.com', 'Excelente manejo de errores. ¿Qué patrones usan?', NOW() - INTERVAL '27 days'),
('Cristina Ortega', 'cristina.o@startup.io', 'Me gusta el sistema de búsqueda. ¿Usan algún search engine?', NOW() - INTERVAL '26 days'),
('Joaquín López', 'joaquin.lopez@corp.com', 'Problema con concurrencia. ¿Manejan locks a nivel de aplicación?', NOW() - INTERVAL '25 days'),
('Diana Martínez', 'diana.m@tech.es', 'El sistema de notificaciones funciona bien. ¿Usan colas?', NOW() - INTERVAL '24 days'),
('Raúl Hernández', 'raul.hernandez@dev.io', 'Interesante arquitectura de microservicios. ¿Cómo manejan la comunicación?', NOW() - INTERVAL '23 days'),
('Sara García', 'sara.garcia@email.com', '¿Tienen métricas de business intelligence?', NOW() - INTERVAL '22 days'),
('Iván Pérez', 'ivan.perez@web.org', 'Excelente manejo de sesiones. ¿Usan JWT o sessions tradicionales?', NOW() - INTERVAL '21 days'),

('Paula Díaz', 'paula.diaz@tech.com', 'Me interesa la accesibilidad. ¿Siguen estándares WCAG?', NOW() - INTERVAL '20 days'),
('Roberto Medina', 'roberto.medina@corp.io', 'Problema con rate limiting. ¿Qué estrategias recomiendan?', NOW() - INTERVAL '19 days'),
('Laura Castro', 'laura.castro@startup.com', 'El sistema de archivos es robusto. ¿Usan CDN?', NOW() - INTERVAL '18 days'),
('Diego Morales', 'diego.morales@dev.com', 'Interesante uso de cache. ¿Redis o Memcached?', NOW() - INTERVAL '17 days'),
('Marta Ruiz', 'marta.ruiz@email.com', '¿Planean añadir más tipos de contenido?', NOW() - INTERVAL '16 days'),
('Santiago López', 'santiago.l@tech.org', 'Excelente manejo de dependencias. ¿Usan Docker multi-stage?', NOW() - INTERVAL '15 days'),
('Natalia Torres', 'natalia.torres@web.com', 'Problema con timezones. ¿Cómo manejan datetime en la BD?', NOW() - INTERVAL '14 days'),
('Hugo González', 'hugo.gonzalez@it.com', 'Me gusta el sistema de plantillas. ¿Desarrollado internamente?', NOW() - INTERVAL '13 days'),
('Andrea Silva', 'andrea.silva@corp.es', 'Interesante enfoque en testing. ¿Tienen cobertura alta?', NOW() - INTERVAL '12 days'),
('Julián Reyes', 'julian.reyes@startup.io', '¿Usan alguna metodología ágil en desarrollo?', NOW() - INTERVAL '11 days'),

('Eva María Díaz', 'eva.diaz@tech.com', 'Excelente documentación para desarrolladores.', NOW() - INTERVAL '10 days'),
('Carlos Alberto Ruiz', 'caruiz@corp.com', 'Problema con backups incrementales. ¿Qué herramientas recomiendan?', NOW() - INTERVAL '9 days'),
('Ana Belén García', 'ana.garcia@web.io', 'Me interesa la parte de SEO. ¿Optimizan para search engines?', NOW() - INTERVAL '8 days'),
('Miguel Santos', 'miguel.santos@dev.org', 'El sistema de alertas funciona bien. ¿Integrado con Slack?', NOW() - INTERVAL '7 days'),
('Carla Rodríguez', 'carla.r@startup.com', 'Interesante uso de machine learning. ¿Para qué casos?', NOW() - INTERVAL '6 days'),
('Fernando José López', 'fernando.jl@tech.es', '¿Planean soporte multi-idioma?', NOW() - INTERVAL '5 days'),
('Lucía Hernández', 'lucia.hernandez@email.com', 'Excelente manejo de estados en la aplicación.', NOW() - INTERVAL '4 days'),
('Pedro Martínez', 'pedro.martinez@corp.io', 'Problema con serialización de datos. ¿Qué formatos usan?', NOW() - INTERVAL '3 days'),
('Sandra Ortega', 'sandra.ortega@web.com', 'Me gusta el sistema de permisos. ¿Role-based?', NOW() - INTERVAL '2 days'),
('Javier Alejandro Torres', 'javier.torres@tech.com', '¿Planean hacer la aplicación open source?', NOW() - INTERVAL '1 day');