services:
  blog-app-1:
    build: ./blog-app
    container_name: blog-app-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.diegoricardo.dev`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=5000"  # 🟢 CORREGIDO: "blog" en vez de "blog-app"
      - "traefik.http.services.blog.loadbalancer.sticky=false"      # 🆕 NUEVO: Deshabilitar sticky sessions
      - "traefik.http.services.blog.loadbalancer.sticky.cookie=false" # 🆕 NUEVO
    environment:
      - DATABASE_URL=postgresql://blog_user:blog_pass@blog-db:5432/blog_db
      - REDIS_URL=redis://redis:6379
      - INSTANCE_NAME=BLUE
      - INSTANCE_COLOR=lightblue
    depends_on:
      - blog-db
      - redis
    networks:
      - web-apps_default

  blog-app-2:
    build: ./blog-app
    container_name: blog-app-2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.diegoricardo.dev`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=5000"  # 🟢 CORREGIDO
      - "traefik.http.services.blog.loadbalancer.sticky=false"      # 🆕 NUEVO
      - "traefik.http.services.blog.loadbalancer.sticky.cookie=false" # 🆕 NUEVO
    environment:
      - DATABASE_URL=postgresql://blog_user:blog_pass@blog-db:5432/blog_db
      - REDIS_URL=redis://redis:6379
      - INSTANCE_NAME=GREEN
      - INSTANCE_COLOR=lightgreen
    depends_on:
      - blog-db
      - redis
    networks:
      - web-apps_default

  blog-app-3:
    build: ./blog-app
    container_name: blog-app-3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.diegoricardo.dev`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=5000"  # 🟢 CORREGIDO
      - "traefik.http.services.blog.loadbalancer.sticky=false"      # 🆕 NUEVO
      - "traefik.http.services.blog.loadbalancer.sticky.cookie=false" # 🆕 NUEVO
    environment:
      - DATABASE_URL=postgresql://blog_user:blog_pass@blog-db:5432/blog_db
      - REDIS_URL=redis://redis:6379
      - INSTANCE_NAME=RED
      - INSTANCE_COLOR=lightcoral
    depends_on:
      - blog-db
      - redis
    networks:
      - web-apps_default

  blog-db:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
    volumes:
      - blog-data:/var/lib/postgresql/data
      - ./init-scripts/blog-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-scripts/seed-data.sql:/docker-entrypoint-initdb.d/02-seed-data.sql
    networks:
      - web-apps_default

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - web-apps_default

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run infra-tunnel
    depends_on:
      - blog-app-1
      - blog-app-2
      - blog-app-3
    volumes:
      - ./e56e9c7f-410a-4512-afd5-4bae2472962b.json:/etc/cloudflared/credentials.json:ro
      - ./config.yml:/etc/cloudflared/config.yml:ro
      - ./cert.pem:/etc/cloudflared/cert.pem:ro
    networks:
      - web-apps_default

volumes:
  blog-data:
  redis-data:

networks:
  web-apps_default:
    external: true