services:
  # App 1 - Blog con formulario de contacto
  blog-app:
    build: ./blog-app
    container_name: blog-app
    environment:
      - DATABASE_URL=postgresql://blog_user:blog_pass@blog-db:5432/blog_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - blog-db
      - redis
    # ⚠️ QUITA el puerto mapeado - Traefik maneja el acceso
    # ports:
    #   - "5001:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.localhost`)"
      - "traefik.http.routers.blog.entrypoints=web"
    networks:
      - webapp-network

  # Bases de datos (solo blog-db por ahora)
  blog-db:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
    volumes:
      - blog-data:/var/lib/postgresql/data
      - ./init-scripts/blog-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-scripts/seed-data.sql:/docker-entrypoint-initdb.d/02-seed-data.sql
    networks:
      - webapp-network

  # Cache
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - webapp-network

volumes:
  blog-data:
  redis-data:

networks:
  webapp-network:
    external: true
    name: web-apps_default