services:
  n8n:
    image: n8nio/n8n:1.115.3
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
      - GENERIC_TIMEZONE=America/New_York
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - web-apps_default

volumes:
  n8n_data:

networks:
  web-apps_default:
    external: true
